### ISSUE TITLE
Script fails on macOS due to line endings

### ISSUE THREAD

**Issue by baffalop** [juliangruber/npm-diff#12]
```
$ npm-diff date-fns 2.9.0 2.17.0
/usr/local/bin/npm-diff: line 2: $'\r': command not found
/usr/local/bin/npm-diff: line 10: $'\r': command not found
: invalid optionpm-diff: line 11: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
/usr/local/bin/npm-diff: line 12: $'\r': command not found
/usr/local/bin/npm-diff: line 14: $'\r': command not found
/usr/local/bin/npm-diff: line 34: syntax error near unexpected token `$'{\r''
'usr/local/bin/npm-diff: line 34: `download(){
```

I removed carriage returns from the file and it works

**Comment by juliangruber** [comment]
I can't reproduce, it works fine on my mac running Big Sur and zsh. Can you share more about your setup?

**Comment by tjallingt** [comment]
I get the exact same error

Mac OS Big Sur 11.1 (20C69)
Shell fish, version 3.1.2
Terminal kitty 0.19.3

**Comment by xiaody** [comment]
Same error and same workaround works.

zsh 5.8 (x86_64-apple-darwin20.0)
node v14.16.0
macOS Big Sur 11.2.3

**Comment by juliangruber** [comment]
I'm puzzled. I can't find any carriage returns in the file, and converting them doesn't change it either. Could it be because of your git setup? See for example https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

**Comment by xiaody** [comment]
> I'm puzzled. I can't find any carriage returns in the file, and converting them doesn't change it either. Could it be because of your git setup? See for example https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

I checked the tarball from `https://registry.npmjs.org/npm-diff/-/npm-diff-1.0.0.tgz`, and it does contain CR.

**Comment by juliangruber** [comment]
Thanks, I hadn't checked the version on npm, I can reproduce now

**Comment by juliangruber** [comment]
1.0.1 fixes this. Thanks for you patience! FTR, I just had to release again
