### ISSUE TITLE
Support .npmrc scopes

### ISSUE THREAD

**Issue by voliva** [juliangruber/npm-diff#5]
When using this tool to compare versions of a package in a private repository declared through npm scopes, it fails without giving any error.

e.g.

```
# .npmrc of the project
@mycompany:registry="https://www.mycompany.com/repository"
```

```
project$ npm-diff @mycompany/mypackage 0.1.0 0.1.1
project$
```

I'm thinking of a local workaround which will be to run `npm show` on both packages before switching to the working tmp folder, but it's rather hacky to raise it as a PR...

**Comment by juliangruber** [comment]
Right, this project currently only supports the main registry. `npm show` does seem to work and gives you the tarball url:

```bash
$ npm show PACKAGE dist.tarball
```

Could you open a PR for this?
