### ISSUE TITLE
installation from NPM

### ISSUE THREAD

**Issue by oprogramador** [juliangruber/npm-diff#6]
It would be great if it was possible to download and install this tool with a single command from `NPM`/`yarn`.

**Comment by juliangruber** [comment]
I agree! Do you want to open a PR which makes it publishable to npm?

**Comment by oprogramador** [comment]
@juliangruber 

Sorry, I missed your question.

It's great it's now installable with NPM.

Anyway I use a Renovate web tool e.g. https://app.renovatebot.com/package-diff?name=@babel%2fcli&from=7.8.4&to=7.11.6
